export const FETCH_USER = "FETCH_USER";
export const FETCH_SPENDINGS = "FETCH_SPENDINGS";
export const CREATE_SPENDING = "CREATE_SPENDING";
export const DELETE_SPENDING = "DELETE_SPENDING";
export const UPDATE_USER_DAILY_LIMIT = "UPDATE_USER_DAILY_LIMIT"
export const FETCH_TODAYS_TOTAL = "FETCH_TODAYS_TOTAL"
export const UPDATE_USER = "UPDATE_USER"